
#[class]
#general = "Alacritty"
#instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

#[visual_bell]
#animation = "EaseOutExpo"
#color = "#e4c9af"
#duration = 0.5

[window]
opacity = 0.9

[window.padding]
x = 15
y = 10

[general]
live_config_reload = true
import = ["/home/tjaboobies/.config/alacritty/catppuccin/catppuccin-frappe.yml"]
