#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
#$scripts/launch_flameshot &
#$scripts/tools/dynamic &

# wallpaper
# $scripts/wall $config/wallpapers/xmascat.png &
hyprpaper &

# effects
$scripts/rgb &

# power management
$scripts/idle &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
