background {
    monitor = 
    #path = ~/.config/hypr/wallpapers/nerv_lock2.jpg
    path = ~/.config/hypr/wallpapers/eva_lock4.jpg
    blur_passes = 2
    contrast = 0.75
    brightness = 0.7
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

input-field {
    monitor = 
    size = 250, 60
    position = 0, -100
    outline_thickness = 3
    dots_center = true
    dots_spacing = 0.2
    dots_size = 0.2
    outer_color = rgba(205, 214, 244, 1)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgba(205, 214, 244, 1)
    fade_on_empty = false
    font_family = FiraCode Nerd Font
    placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
    hide_input = false
    halign = center
    valign = center
}

label {
    monitor = 
    text = cmd[update:1000] date +"%-I:%M%p"
    color = rgba(205, 214, 244, 1)
    font_size = 50
    font_family = FiraCode Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

label {
    text = cmd[update:30000] ~/.config/hypr/scripts/get_weather.sh
    font_size = 20
    font_family = FiraCode Nerd Font
    color = rgba(205, 214, 244, 1)
    position = 0, 50
    halign = center
    valign = center
}
